<a href="https://colab.research.google.com/github/Neel7317/Deep-Learning-/blob/master/%20Create%20a%20simple%20Neural%20Network%20From%20Scratch%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##### Create a simple Neural Network From Scratch

In [ ]:
import numpy as np

In [ ]:
### Create the input samples
input_samples = np.array([[0,0,1],
                         [1,1,1],
                         [1,0,1],
                         [0,1,1]]) 

In [ ]:
input_samples

In [ ]:
### Create the input samples
output_samples = np.array([[0],[1],[1],[0]]) 

In [ ]:
output_samples

In [ ]:
np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [ ]:
#### Activation Function (Sigmoid)
def activation(x):
  return 1 / (1 + np.exp(-x))

In [ ]:
activation(2)

1.0

In [ ]:
def derivative(x):
  return x * (1-x)

In [ ]:
for i in range(500):
  mul = np.dot(input_samples,weights)   ###dot matrix multiplication
  outputs = activation(mul)
  error = output_samples - outputs
  adjustments = error * derivative(outputs)    #### Gradient Descent 
  weights += np.dot(input_samples.T,adjustments)   ### Backpropogation

In [ ]:
outputs.round()

array([[0.],
       [1.],
       [1.],
       [0.]])

In [ ]:
error

array([[-0.03374826],
       [ 0.02740406],
       [ 0.02200419],
       [-0.02713317]])